### ISSUE TITLE
Support conventional changelog format

### ISSUE THREAD

**Issue by romanr** [aldrin/git-changelog#17]
I couldn't make it work because it seems that it's hardcoded to message format 

```
feature: description
```

At this point the most commonly used format is

```
feature(module): description
```

**Comment by aldrin** [comment]
Thank you for your interest in this tool. I hope you find it useful. 🙂
The _tagging_ format is already what you are looking for. Please see:

https://github.com/aldrin/git-changelog/blob/master/src/assets/sample-commit.message#L24-L28

The general form is: `- category(scope): <markdown>` where you can define categories and scope as they seem best for your project. The tags needs a prefix `-` to trigger parsing because unlike other tools there are no constraints on the message text.  

Hope that helps.

**Comment by romanr** [comment]
Oh! I finally realized that to use this tool you have to actually _tag_ every commit you want in the changelog.  
That's not really helping but creating more work, going to all the commits and tagging.  
Isn't the whole point of automated changelog generation to make it hands-off generated from commit messages?  
This is also not really supporting conventional change logging because tagging every commit is not something that conventionally done.  
Maybe you can look into making an option for it to parse actual commit messages instead of tags.

**Comment by aldrin** [comment]
>  I finally realized that to use this tool you have to actually tag every commit 

That's not right. See the [Usage](https://github.com/aldrin/git-changelog/blob/master/README.md#usage) section in the README. By "tagging", I meant adding those annotations in your commit messages which are used to categorize the changelog. 

If you want to see it in action:

```bash
/tmp » git clone https://github.com/aldrin/git-changelog        
/tmp » cd git-changelog
/tmp/git-changelog [master] » git changelog
# v0.2.0..HEAD (2018-02-17)

- [Restructure inputs and outputs](https://github.com/aldrin/git-changelog/pull/12)
- [Accept all that `git log` can accept to pick commits](https://github.com/aldrin/git-changelog/pull/15)

### Features
    
- Markdown output is tidier as includes revision range
  and timestamps in the generated report. The report can also be
  produced to JSON to support dynamic renderings (if required).

- The tool now accepts `git log` arguments to choose
    commits to be included in the report. For example:
  
    ```bash
    # My changes in reverse chronological order
    > git changelog -- --author aldrin --reverse
    ```
  
    ```bash
    # All changes since yesterday
    > git changelog -- --since yesterday
    ```
  
    Note that you need a `--` before you begin `git log` arguments.

- Values for the command line arguments `--template` and
    `--remote` can now be specified in configuration file as well.

### Breaking Changes
    
- The input to the tool is rearranged and now separates
  project conventions from output preferences under separate YAML
  nodes. This implies that external configuration files would
  require some tweaks. See [.changelog.yml] and
  [src/assets/changelog.yml] for the new format.
```

**Comment by PartyLich** [comment]
> The tags needs a prefix `-` to trigger parsing because unlike other tools there are no constraints on the message text.

This constraint makes this tool unusable for projects implementing [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). The "tags" (a very confusing choice of name given its use in git) in conventional commits follow a machine readable spec, but they don't include a leading '- '. 

Assuming this project isn't dead (last open issue is 3 years old, and had an expected fix of that weekend :/ ), the current configuration options do not support this use case.
